name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/wrapper-validation@v4
      - name: Check local deployment
        run: ./gradlew build deployLocal
      - name: Check sample app
        run: cd tests && ../gradlew sample:assembleDebug